feat: 협업지점 소개 페이지 전체 리스트 조회 및 스크롤 이동
Upbrella/Upbrella_front pull request #114
Opened 2023-09-16 07:03 UTC by chaeyeon-yang

### PR Type

- [x] 기능 개발 (Feature)
- [ ] 코드 스타일 변경 (Code style update) (formatting, local variables)
- [x] 화면 작업 (Style, CSS)
- [x] 리팩토링 (no functional changes, no api changes)
- [ ] 버그수정 (Bugfix)
- [ ] 빌드, 배포 관련 변경 (Build, Deploy)
- [ ] 문서 작업 (Docs)
- [ ] 그 외 (ETC)

## 작업 내용

- 협업 지점 소개 페이지 전체 협업 지점 목록 조회
- 상단의 소분류 태그 선택시 해당 소분류의 협업지점이 화면 상단에 오도록 자동 스크롤

## Before

## After

<img width="1374" alt="스크린샷 2023-09-16 오후 3 50 43" src="https://github.com/UPbrella/UPbrella_front/assets/69382168/8569c878-31d1-425e-9173-28a0d08abed4">

<img width="1489" alt="스크린샷 2023-09-16 오후 3 50 50" src="https://github.com/UPbrella/UPbrella_front/assets/69382168/fe5e11aa-07f3-4479-aa5b-423d66268ccd">

## To Reviewers (참고 사항, 첨부 자료 등)

- 화면에서 Null 이미지는 백엔드에서 보내주는 것이 아닌 이미지가 오지 않은 경우 에러가 발생해 임의로 넣어놓은 사진입니다.
- 이미지는 nullable이라고 하셨고 아직 테스트데이터라 적용안해놓으신 것 같습니다.
- 스토어 컴포넌트 클릭시 상세정보를 조회하고자 했는데 404에러가 떠서 백엔드 분들께 문의 드린 상태입니다.
- 해당 이슈 합의 후에 다시 협업 지점 상세조회 로직을 짜서 완성하도록 하겠습니다.

2023-09-16 17:04 UTC, ShinChanU commented on src/api/storeApi.ts
> +  ADMIN_STORES: (id?: number) => (id ? `/stores/${id}` : `/stores`),
확인해보니까 이곳 17, 18, 19 라인의 API 는 어드민 > 협업지점관련 API 라서 `/admin`이 있어야 할 것 같습니다 ! 지금 이상태에서는 404 에러가 나오네요 !

@chaeyeon-yang

2023-09-16 17:07 UTC, ShinChanU commented on src/components/pages/rentalOffice/RentalOfficePage.tsx
> +  useEffect(() => {
이 `useEffect` 문의 역할은 없어보이네요 !
지워도 좋을 것 같습니다 !

@chaeyeon-yang

2023-09-16 17:09 UTC, ShinChanU requested changes
`RentalLocationPage.tsx` 파일에서 `LocationClassificationBtn` 컴포넌트에 대한 타입에러도 있는 것 같습니다 !

@chaeyeon-yang

2023-09-17 15:55 UTC, chaeyeon-yang commented on src/api/storeApi.ts
> +  ADMIN_STORES: (id?: number) => (id ? `/stores/${id}` : `/stores`),
감사합니다 수정했습니다!

2023-09-17 15:55 UTC, chaeyeon-yang commented on src/components/pages/rentalOffice/RentalOfficePage.tsx
> +  useEffect(() => {
네! 현재 필요한 코드가 아닌 것 같으니 지우겠습니다!

2023-09-17 15:55 UTC, chaeyeon-yang commented
> `RentalLocationPage.tsx` 파일에서 `LocationClassificationBtn` 컴포넌트에 대한 타입에러도 있는 것 같습니다 !
> 
> @chaeyeon-yang

저번 pr의 문제점이 이번에도 중복되는 것 같네요! 수정했습니다

2023-09-17 17:08 UTC, ShinChanU commented on src/api/storeApi.ts
> +  ADMIN_STORES: (id?: number) => (id ? `/admin/stores/${id}` : `/stores`),
```tsx
ADMIN_STORES: (id?: number) => (id ? `/admin/stores/${id}` : `/admin/stores`)
```

뒤에도 `/admin/stores`로 변경해주셔야할 것 같아요 !

@chaeyeon-yang

2023-09-18 02:31 UTC, chaeyeon-yang commented
> `RentalLocationPage.tsx` 파일에서 `LocationClassificationBtn` 컴포넌트에 대한 타입에러도 있는 것 같습니다 !
> 
> @chaeyeon-yang

죄송합니다 ㅠㅠㅠ 수정했습니다!

2023-09-18 03:38 UTC, heehminh commented
<img width="1511" alt="image" src="https://github.com/UPbrella/UPbrella_front/assets/76530562/b15dc60c-8320-4f5a-b39f-7c88dbd380e9">

협업 지점 소개 페이지에서 분류 태그 api 호출이 안되는 것 같습니다

@chaeyeon-yang

2023-09-18 11:30 UTC, chaeyeon-yang commented on src/api/storeApi.ts
> +  ADMIN_STORES: (id?: number) => (id ? `/admin/stores/${id}` : `/stores`),
수정했습니다!

2023-09-18 11:55 UTC, ShinChanU approved these changes
고생하셨습니다 !!

2023-09-19 01:37 UTC, heehminh approved these changes

2023-09-19 05:17 UTC, LeeJSYS approved these changes
고생하셨습니다!

2023-09-19 05:17 UTC, merged