Design/mypage/05
Upbrella/Upbrella_front pull request #122
Opened 2023-09-18 13:31 UTC by LeeJSYS

### PR Type

- [X] 기능 개발 (Feature)
- [ ] 코드 스타일 변경 (Code style update) (formatting, local variables)
- [ ] 화면 작업 (Style, CSS)
- [ ] 리팩토링 (no functional changes, no api changes)
- [ ] 버그수정 (Bugfix)
- [ ] 빌드, 배포 관련 변경 (Build, Deploy)
- [ ] 문서 작업 (Docs)
- [ ] 그 외 (ETC)

## 작업 내용
- 계좌 등록, 삭제, 변경 기능 구현 했습니다.

## Before

## After
<img width="1440" alt="image" src="https://github.com/UPbrella/UPbrella_front/assets/120862683/e3a765ec-8ff1-4db9-8213-cffc6e9b8841">

## To Reviewers (참고 사항, 첨부 자료 등)

2023-09-18 14:30 UTC, ShinChanU approved these changes
고생하셨습니다 !!! 👏👏👏

이렇게 코드 작성하셔도 훌륭하지만, `react-query`랑 `react-hot-toast` 와 같은 라이브러리도 적극 활용해보시면 더 좋을 것 같네요 !!

좋은 글이 있어서 남겨드립니다 ㅎㅎ
[리액트 쿼리 정리글](https://github.com/ssi02014/react-query-tutorial#-tanstack-queryreact-query-v4)

2023-09-19 01:59 UTC, chaeyeon-yang approved these changes
수고하셨습니다!!!!

2023-09-19 03:44 UTC, heehminh commented
준석님 제가 지금 확인해봤을 땐 환급계좌 정보가 없는 경우엔 잘 동작하는 것 같은데 환급계좌 정보가 이미 있고 변경하려는 경우엔 잘 동작하지 않는 것 같습니다! 

https://github.com/UPbrella/UPbrella_front/assets/76530562/9ba06f4f-6dc1-438a-8782-4cecb16b6d51

그리고 사소하지만 계좌 변경, 계좌 등록 버튼은 border 가 없는 것 같습니다

2023-09-19 04:59 UTC, chaeyeon-yang requested changes
지금 확인해보니 저도 은행명을 바꾸면 계좌 변경이 안되네요!

2023-09-21 08:21 UTC, LeeJSYS commented
> 고생하셨습니다 !!! 👏👏👏
> 
> 이렇게 코드 작성하셔도 훌륭하지만, `react-query`랑 `react-hot-toast` 와 같은 라이브러리도 적극 활용해보시면 더 편리하실 것 같네요 !!
> 
> 좋은 글이 있어서 남겨드립니다 ㅎㅎ [리액트 쿼리 정리글](https://github.com/ssi02014/react-query-tutorial#-tanstack-queryreact-query-v4)

감사합니다 찬우님. 중요 기능 개발 마치는대로 리펙토링해보겠습니다. 
남겨주신글과 찬우님께서 로그인 파트 수정해주신 코드 참고해서 개발해보겠습니다!! 
감사합니다 :)

2023-09-23 02:55 UTC, LeeJSYS commented
> 준석님 제가 지금 확인해봤을 땐 환급계좌 정보가 없는 경우엔 잘 동작하는 것 같은데 환급계좌 정보가 이미 있고 변경하려는 경우엔 잘 동작하지 않는 것 같습니다!
> 
>  2023-09-19.12.40.30.mov 
> 그리고 사소하지만 계좌 변경, 계좌 등록 버튼은 border 가 없는 것 같습니다
> 
> @LeeJSYS

@heehminh 
계좌변경 관련 오류 수정했습니다.
계좌변경, 계좌 등록 버튼은 디자인상에서 border가 없습니다. 감사합니다!

2023-09-23 02:55 UTC, LeeJSYS commented
> 지금 확인해보니 저도 은행명을 바꾸면 계좌 변경이 안되네요!

@chaeyeon-yang 
관련오류 수정했습니다!

2023-09-23 04:00 UTC, heehminh commented
> > 준석님 제가 지금 확인해봤을 땐 환급계좌 정보가 없는 경우엔 잘 동작하는 것 같은데 환급계좌 정보가 이미 있고 변경하려는 경우엔 잘 동작하지 않는 것 같습니다!
> > 2023-09-19.12.40.30.mov
> > 그리고 사소하지만 계좌 변경, 계좌 등록 버튼은 border 가 없는 것 같습니다
> > @LeeJSYS
> 
> @heehminh 계좌변경 관련 오류 수정했습니다. 계좌변경, 계좌 등록 버튼은 디자인상에서 border가 없습니다. 감사합니다!

<img width="1096" alt="image" src="https://github.com/UPbrella/UPbrella_front/assets/76530562/3ee652e2-29cd-4909-9e96-620f4d5ef0dc">

여기엔 border 를 하셨길래 남겼습니다! @LeeJSYS

2023-09-23 04:00 UTC, heehminh approved these changes

2023-09-24 05:00 UTC, chaeyeon-yang approved these changes
수고많으셨습니다 ~~~~~!!!

2023-09-24 05:00 UTC, merged