fix: 어드민 > 협업지점 활성화여부 기능 수정
Upbrella/Upbrella_front pull request #143
Opened 2023-09-22 17:41 UTC by ShinChanU

### PR Type
- [x] 기능 개발 (Feature)
- [x] 코드 스타일 변경 (Code style update) (formatting, local variables)
- [x] 화면 작업 (Style, CSS)
- [x] 리팩토링 (no functional changes, no api changes)
- [x] 버그수정 (Bugfix)

## 작업 내용
어드민 > 협업 지점 관리 페이지 작업입니다.
- 활성화 여부 모달에서 삭제, 테이블에서 수정 가능 (API 2개 추가)
- 이미지, 활성여부 칼럼 위치 옮김
- 테이블 UI 리팩토링

## Before
<img width="1120" alt="image" src="https://github.com/UPbrella/UPbrella_front/assets/76439533/2832e367-048d-4533-a17a-ff503cbfc60f">

## After
<img width="974" alt="image" src="https://github.com/UPbrella/UPbrella_front/assets/76439533/cb7fac83-f8c3-4c3c-bf0b-08dba83aa2b3">

## To Reviewers (참고 사항, 첨부 자료 등)

2023-09-23 04:05 UTC, heehminh approved these changes
수고하셨습니다👍

2023-09-24 05:03 UTC, chaeyeon-yang approved these changes
이번 주 내내 정말 수고 많으십니다 .. 👏✨✨

2023-09-25 06:54 UTC, LeeJSYS approved these changes

2023-09-25 06:54 UTC, LeeJSYS commented on src/utils/admin/storeHelpers.tsx
> +export const STORE_ADMIN_TABLE: Record<TStoreTableKey, { label: string; minWidth?: string }> = {
고생많으셨습니다!

<img width="558" alt="image" src="https://github.com/UPbrella/UPbrella_front/assets/120862683/330ecd7d-1449-49c5-8881-ca5e6e0da56f">
빌드에러가 몇개 있는 것 같아요

2023-09-25 06:56 UTC, LeeJSYS requested changes
고생많으셨습니다!

<img width="558" alt="image" src="https://github.com/UPbrella/UPbrella_front/assets/120862683/330ecd7d-1449-49c5-8881-ca5e6e0da56f">

빌드에러가 몇개 있는 것 같아요

2023-09-25 07:23 UTC, chaeyeon-yang commented
> [Sep 25, 2023 ](#pullrequestreview-1641446338)
> [ View reviewed changes ](/UPbrella/UPbrella_front/pull/143/files/46ac83e828294c0a82ee1833e98ab1c4f9d1978f)

@LeeJSYS 제가 만든 컴포넌트에서 난 에러도 있는 것 같아서 그 부분은 제가 다음 pr에 수정해서 올리겠습니다!

2023-09-25 11:19 UTC, LeeJSYS approved these changes

2023-09-25 11:19 UTC, merged