Rental location detail
Upbrella/Upbrella_front pull request #19
Opened 2023-07-29 14:44 UTC by chaeyeon-yang

### PR Type

- [ ] 기능 개발 (Feature)
- [ ] 코드 스타일 변경 (Code style update) (formatting, local variables)
- [x] 화면 작업 (Style, CSS)
- [ ] 리팩토링 (no functional changes, no api changes)
- [ ] 버그수정 (Bugfix)
- [ ] 빌드, 배포 관련 변경 (Build, Deploy)
- [ ] 문서 작업 (Docs)
- [ ] 그 외 (ETC)

## 작업 내용
- 컴포넌트 합쳐서 대여소 위치 페이지 생성
- 협업지점 상세 카드의 푸터 생성
- 기타 자잘한 스타일 수정

## Before

## After

<img width="1436" alt="스크린샷 2023-07-29 오후 6 54 55" src="https://github.com/UPbrella/UPbrella_front/assets/69382168/4f1c76db-0e65-4597-8d8a-0cf16e782c52">

<img width="1037" alt="스크린샷 2023-07-29 오후 11 39 34" src="https://github.com/UPbrella/UPbrella_front/assets/69382168/a6b416c2-8524-4ad0-98da-bb02170052db">

## To Reviewers (참고 사항, 첨부 자료 등)

- 제가 깃 브랜치 설정에서 꼬여서.. 의도치 않게 다른 파일들까지 같이 커밋하게 되었습니다 ㅜㅜ 감안하고 봐주세요 죄송합니다..

2023-07-29 14:48 UTC, heehminh commented on src/components/templates/RentalInfo.tsx
> +    <div className="flex-col ㅎ메">
오타난 것 같습니다

2023-07-29 14:54 UTC, heehminh requested changes

2023-07-29 14:54 UTC, heehminh commented on src/routes/layoutRouter.ts
> +// >>>>>>> f5e72423d614d5b5ff293e4896b2d3995835ce4d
이 부분 한번 정리해주시면 좋을 것 같습니다!

2023-07-29 15:08 UTC, ShinChanU approved these changes

2023-07-30 00:25 UTC, LeeJSYS approved these changes

2023-07-30 00:32 UTC, LeeJSYS commented on src/components/molecules/CardFooter/CardFooterLabel/CardFooterLabel.tsx
> +import React from "react";
이부분은 지금은 필요없어 보이네요..!

2023-07-30 10:33 UTC, chaeyeon-yang commented on src/components/templates/RentalInfo.tsx
> +    <div className="flex-col ㅎ메">
헉.. 수정하겠습니다!

2023-07-30 10:38 UTC, heehminh approved these changes

2023-07-30 12:33 UTC, merged