style: 페이지 전역 max-width, padding 설정
Upbrella/Upbrella_front pull request #21
Opened 2023-07-29 15:36 UTC by ShinChanU

### PR Type

- [ ] 기능 개발 (Feature)
- [ ] 코드 스타일 변경 (Code style update) (formatting, local variables)
- [x] 화면 작업 (Style, CSS)
- [ ] 리팩토링 (no functional changes, no api changes)
- [ ] 버그수정 (Bugfix)
- [ ] 빌드, 배포 관련 변경 (Build, Deploy)
- [ ] 문서 작업 (Docs)
- [ ] 그 외 (ETC)

## 작업 내용
- 페이지 통일을 위해 전역적으로 `max-witdh`와 `padding`을 설정했습니다.
-  max-witdh : 1440px
-  padding-x: 40

## Before

## After
![image](https://github.com/UPbrella/UPbrella_front/assets/76439533/68660361-446d-4797-88b9-c959af2e68ed)

## To Reviewers (참고 사항, 첨부 자료 등)
피그마 참고해서 수정했는데 혹시나 다른 값이면 말씀해주세요 !

2023-07-29 15:40 UTC, heehminh requested changes

2023-07-29 15:40 UTC, heehminh commented on src/App.tsx
> +      <div className="max-w-[1440px] px-40 mx-auto">
max width도 `max-w-1440` 으로 작성해주시면 됩니다!

2023-07-29 15:45 UTC, ShinChanU commented on src/App.tsx
> +      <div className="max-w-[1440px] px-40 mx-auto">
`tailwind.config.js` 에 `width` 의 경우 0부터 1000까지 만 포맷팅이 되어있는 것 같아서 이렇게 했어요 !
한번 확인해주시겠어요?

@heehminh

2023-07-29 15:54 UTC, heehminh commented on src/App.tsx
> +      <div className="max-w-[1440px] px-40 mx-auto">
앗 tailwind.config.js 에 `const px0_1500 = { ...Array.from(Array(1501)).map((_, i) => `${i}px`) };` 이런식으로 설정해주시고, extend에 `width: px0_1500` 로 변경해주시면 될거에요! (1500은 임의적인 숫자입니다)

2023-07-29 15:54 UTC, heehminh approved these changes

2023-07-30 10:34 UTC, chaeyeon-yang approved these changes

2023-07-30 10:40 UTC, merged