feat: login atoms UI 개발
Upbrella/Upbrella_front pull request #25
Opened 2023-07-31 07:41 UTC by LeeJSYS

### PR Type

- [ ] 기능 개발 (Feature)
- [ ] 코드 스타일 변경 (Code style update) (formatting, local variables)
- [V ] 화면 작업 (Style, CSS)
- [ ] 리팩토링 (no functional changes, no api changes)
- [ ] 버그수정 (Bugfix)
- [ ] 빌드, 배포 관련 변경 (Build, Deploy)
- [ ] 문서 작업 (Docs)
- [ ] 그 외 (ETC)

## 작업 내용
로그인 버튼, 타이틀 만들었습니다.
테일윈드랑 스토리북 공부하면서 하다보니 속도가 조금 느리네요. 빨리 속도 올려보도록하겠습니다!!!!

## Before
None

## After
<img width="346" alt="image" src="https://github.com/UPbrella/UPbrella_front/assets/120862683/701d116b-26ff-4073-9f28-69596d59da83">
<img width="103" alt="image" src="https://github.com/UPbrella/UPbrella_front/assets/120862683/37bf4bb1-86b9-43d2-8c32-789ee6ff4843">

## To Reviewers (참고 사항, 첨부 자료 등)

1. 아토믹 디자인 패턴에 맞게 컴포넌트를 쪼개보았습니다. 저희 노션에 있는 카카오엔터 블로그 읽어보고 다른 분들이 나누어두신것 참고하고 쪼개보았습니다. 로그인 버튼과 타이틀을 묶은 로그인 폼은 organisms에 추가해야할 것 같은데 이게 맞겠지요?
2. 테일윈드 사용부분에서 문제 있으면 코멘트 주시면 감사하겠습니다.
3. kakaoblack을 tailwind config에 추가했습니다. 피그마를 둘러보니 카카오 로그인 텍스트에만 해당 black 색이 들어가는 것 같아서 이렇게 추가했습니다. 이렇게 하면 안되는 거면 알려주세요. (잘몰라서요)
4. 이전 PR들 보니 assignees, reviewers에 추가해야 알람간다고 해서 추가해봤습니다.
5. 채연님의 [Feat] imgswiper 컴포넌트 개발 PR에 코멘트로 찬우님께서 import 를 절대경로로 맞추는 건 어떻게 생각하시나요라고 하신 부분은 모든 경로에 해당되는 것인가요? 코멘트주시면 감사하겠습니다.
6. 소통을 github로 한다는게 이렇게 PR이나 코멘트에 질문하고 그런건가요? 
7. 처음해봐서 다 새롭습니다. 오늘 부트캠프에서 개발자는 소통이라고 하는게 꼭 언어적 소통말고 협업툴이나 문서를 통한 소통도 해당된다고 하더라구요. 이런게 거기에 해당되는 건가요?
8. 저번에 민희님께서 svg, png중에 svg?를 써야지 하셨는데 그런건가요? 아니면 부먹, 찍먹 이런 문제인가요?
9. PR 대부분을 읽어보긴했는데 아직 이해하지 못한 부분이 많습니다. 추후에 질문드릴게요.

질문이 많아서 죄송하고 깃헙으로 이렇게 질문하는게 아니라면 앞으로는 슬랙으로 질문드릴게요
감사합니다!!!!

2023-07-31 11:17 UTC, ShinChanU approved these changes
몇 줄 안되는 제 생각 적습니다 ㅎㅎ

1. 맞는 것 같습니다 !
2. 넵! 테일윈드는 공식문서를 참고하면서, 적용해보시고, 개발자 도구로 classname에 맞는 스타일이 잘 적용되었는지 확인하면 좋을 것 같습니다.
3. 상관없습니다. 괜찮은 것 같아요.
4. 제가 알기로는, assignee은 책임자 (본인), reviewers는 코드 리뷰어 (본인외에 전부) 정도로 알고 있어요!
5. 넵! 예전에 제가 슬랙 프론트엔드 방에도 올린 적이 있는데, 아마 설정만 잘 되어 있으면 import 시에 자동으로 절대 경로 설정해줄거예요 !
6. 네, 저희는 코드 머지가 PR로 진행되니, 리뷰어들이 코드를 보고 궁금하거나 요청사항있으면 코멘트로 소통하면 그것이 깃허브로 소통한다는 의미 아닐까요?
7. 네 깃허브도 그렇고, 백엔드분들께서 만들어주신 API 명세서, 저희끼리 맞췄던 코드 컨벤션 등도 그런 소통의 문서라고 생각합니다.
8. svg, png, jpg 의 차이를 찾아보시면 좋을 것 같습니다. 개인적으로는 이미지 형식의 성격 자체가 달라서 사용목적에 따라 맞춰 쓰는게 맞지 않을까라는 생각이 있어요.

@LeeJSYS

2023-07-31 12:28 UTC, heehminh approved these changes
앗 제가 그때 svg를 사용해야 한다고 말한 이유는 마커 이미지를 가져올 때 마커가 모양은 모두 같은데 색, 크기가 달라서이기 때문이였어요! svg로 받아오면 색과 크기를 지정할 수 있거든요!! 

수고 많으셨습니다 :)

2023-07-31 12:34 UTC, heehminh requested changes

2023-07-31 12:34 UTC, heehminh commented on src/components/atoms/Login/LoginButton/index.tsx
> +    <div className="max-w-xs">
카카오로 3초 만에 시작하기 label 왼쪽에 카카오 아이콘 추가해야 할 것 같습니다! 

디자인을 늦게 확인해서 approve 후에 리뷰 남겨서 죄송합니다

2023-08-01 12:28 UTC, LeeJSYS commented on src/components/atoms/Login/LoginButton/index.tsx
> +    <div className="max-w-xs">
@heehminh 
제가 확인이 늦었습니다 추가했습니다!! 감사합니다

2023-08-01 12:45 UTC, LeeJSYS commented on src/components/atoms/Login/LoginButton/index.tsx
> +    <div className="max-w-xs">
@heehminh 
확인이 늦어서 죄송합니다. 추가했습니다!! 
아이콘 같은 경우에는 피그마에서 svg 파일 export해서 사용하면 되죠?? 수정사항은 그렇게 진행했습니다

2023-08-01 12:50 UTC, heehminh commented on src/components/atoms/Login/LoginButton/index.tsx
> +    <div className="max-w-xs">
네 맞습니다!!

2023-08-01 14:43 UTC, chaeyeon-yang approved these changes
지난 코드 꼼꼼히 읽어주신 것 같아 감사합니다! 아토믹하게 코드 잘 짜신 것 같아요 수고많으셨습니다! 🙂✨

2023-08-02 15:16 UTC, heehminh approved these changes

2023-08-02 15:16 UTC, merged