Style/mypage/01
Upbrella/Upbrella_front pull request #75
Opened 2023-08-30 11:48 UTC by LeeJSYS

### PR Type

- [ ] 기능 개발 (Feature)
- [ ] 코드 스타일 변경 (Code style update) (formatting, local variables)
- [ ] 화면 작업 (Style, CSS)
- [ ] 리팩토링 (no functional changes, no api changes)
- [ ] 버그수정 (Bugfix)
- [ ] 빌드, 배포 관련 변경 (Build, Deploy)
- [ ] 문서 작업 (Docs)
- [ ] 그 외 (ETC)

## 작업 내용
mypage에서 공통으로 사용되는 left nav 와 이용내역의 기본 UI 를 개발하였습니다.

현재 로그인, 회원가입 관련 API 수정이 완료되지 않아서 mypage UI 개발을 먼저하고 있습니다.
로그인 관련 api가 완성되어야 mypage 관련 api도 사용할 수 있는 상황입니다.

## Before
없음

## After
<img width="636" alt="image" src="https://github.com/UPbrella/UPbrella_front/assets/120862683/d191413c-a2d0-41c1-ac17-6f187f9cf75d">
<img width="1113" alt="image" src="https://github.com/UPbrella/UPbrella_front/assets/120862683/39f3c08d-db66-415c-9a01-7d8028e7e7c5">

## To Reviewers (참고 사항, 첨부 자료 등)

#74

2023-08-31 09:16 UTC, chaeyeon-yang commented on src/components/atoms/Mypage/MypageNavSection/index.tsx
> +      <p className="text-black text-18 font-semibold leading-24">{navName}</p>
isClick과 onClick을 나눈 이유가 궁금합니다!

2023-08-31 09:16 UTC, chaeyeon-yang commented on src/components/atoms/Mypage/ProfileName/index.tsx
> +      <div className="flex flex-col justify-center items-center mb-24 text-14 font-normal leading-20">
이 부분은 텍스트 컬러 gray-700이 적용 안된 것 같습니다!

2023-08-31 09:16 UTC, chaeyeon-yang commented on src/components/atoms/Mypage/MypageRentSection/index.tsx
> +              <div key={index} className="flex">
이 부분도 text gray-700 컬러 들어가면 될 것 같습니다

2023-08-31 09:16 UTC, chaeyeon-yang commented on src/components/atoms/Mypage/ProfileName/index.tsx
> +      <div className="flex flex-col justify-center items-center mb-24 text-14 font-normal leading-20">
그리고 return 문 나누신 이유가 궁금합니다!

2023-08-31 11:47 UTC, ShinChanU approved these changes

2023-08-31 11:48 UTC, heehminh requested changes

2023-08-31 11:48 UTC, heehminh commented on src/components/atoms/Mypage/ProfileRent/index.tsx
> +      <div className="flex p-20 border bg-primary-100 border-primary-300 border-solid rounded-12">
이 부분에서 atom 으로 만든 MyPageRentSection 재사용하시면 될 것 같습니다!

2023-08-31 11:48 UTC, heehminh commented on src/components/atoms/SignUp/SignUpFormInputBankName/index.tsx
> +        <ExpandMoreIcon className="text-gray-700" onClick={onClick} />
아이콘보다 전체 박스를 클릭했을 때 onClick 이벤트를 등록하는 게 어떨까 싶습니다 사용자가 클릭하기에 아이콘이 너무 작은 것 같아서요!

2023-09-04 03:35 UTC, LeeJSYS commented on src/components/atoms/Mypage/MypageNavSection/index.tsx
> +      <p className="text-black text-18 font-semibold leading-24">{navName}</p>
isClick에는 몇번째 메뉴가 눌렸나에 대한 정보를 담고 onClick에는 메뉴 버튼이 눌렸을때 적절한 페이지로 navigate시키려 했는데 isClick, onClick 두가지가 다 필요할 것 같다는 판단이 들어서 두개 다 넣어놓긴했습니다.
추후에 코드를 짜면서 필요없으면 없애도록 할게용

2023-09-04 04:10 UTC, LeeJSYS commented on src/components/atoms/Mypage/ProfileName/index.tsx
> +      <div className="flex flex-col justify-center items-center mb-24 text-14 font-normal leading-20">
`연우님은 비닐우산이 썩는~` 이부분이 gray-700이 적용되지 않아 보이시나요? 제쪽에서는 적용이 되는 것 같아보이는데 다시 확인해보겠습니다.
그리고 return 문 나눈부분은 어떤 부분을 말씀하신걸까요??

2023-09-04 04:10 UTC, LeeJSYS commented on src/components/atoms/SignUp/SignUpFormInputBankName/index.tsx
> +        <ExpandMoreIcon className="text-gray-700" onClick={onClick} />
네 알겠습니다 좋은 생각인것같습니다!

2023-09-04 04:10 UTC, LeeJSYS commented on src/components/atoms/Mypage/MypageRentSection/index.tsx
> +              <div key={index} className="flex">
네 반영하겠습니다!!

2023-09-04 04:10 UTC, LeeJSYS commented on src/components/atoms/Mypage/ProfileRent/index.tsx
> +      <div className="flex p-20 border bg-primary-100 border-primary-300 border-solid rounded-12">
네 피드백 감사합니다!

2023-09-04 12:44 UTC, heehminh approved these changes

2023-09-05 00:13 UTC, chaeyeon-yang commented on src/components/atoms/Mypage/ProfileName/index.tsx
> +      <div className="flex flex-col justify-center items-center mb-24 text-14 font-normal leading-20">
@LeeJSYS 아 ProfileRent 부분의 return 문을 말씀드리고 싶었는데 코멘트를 다른 파일에 남겼네요!!

2023-09-05 00:14 UTC, chaeyeon-yang approved these changes

2023-09-05 00:14 UTC, merged