feat: 모바일 헤더 메뉴
Upbrella/Upbrella_front pull request #76
Opened 2023-08-30 23:30 UTC by chaeyeon-yang

### PR Type

- [x] 기능 개발 (Feature)
- [ ] 코드 스타일 변경 (Code style update) (formatting, local variables)
- [x] 화면 작업 (Style, CSS)
- [ ] 리팩토링 (no functional changes, no api changes)
- [ ] 버그수정 (Bugfix)
- [ ] 빌드, 배포 관련 변경 (Build, Deploy)
- [ ] 문서 작업 (Docs)
- [ ] 그 외 (ETC)

## 작업 내용
- 대여지점 대분류, 소분류 api 확인
- 모바일(테블렛, 폰) 헤더 메뉴 생성
- 로그인/로그아웃에 따른 메뉴 생성

## Before

## After
- 모바일 헤더(로그아웃)
<img width="683" alt="스크린샷 2023-08-31 오전 8 28 47" src="https://github.com/UPbrella/UPbrella_front/assets/69382168/719ca29c-0037-4d53-930d-9f237ffb878e">

- 모바일 헤더(로그인)
<img width="681" alt="스크린샷 2023-08-31 오전 8 29 25" src="https://github.com/UPbrella/UPbrella_front/assets/69382168/76cad046-c68d-491b-9e9d-58ec860eaa53">

## To Reviewers (참고 사항, 첨부 자료 등)
- 현재 네이버지도가 배포환경에서는 뜨는데 localhost에서 인증이 실패해 제대로 된 테스트가 안되고있습니다! 금방 해결해서 관련 api 통신 후 pr 올리겠습니다
- 모바일 헤더 메뉴에서 로그인여부는 props를 통해 임의 설정했습니다.

2023-08-31 11:44 UTC, ShinChanU commented on src/lib/axios.ts
> +  baseURL: "http://43.202.94.218:8080",
다시 원래 상태로 돌려주시면 감사할것 같습니다 ㅎ

@chaeyeon-yang

2023-08-31 11:44 UTC, ShinChanU commented on src/components/atoms/LocationClassificationBtn/index.tsx
> +  classifications: {
이 부분 `TClassification` 로 대체 가능할 것 같은데 한번 확인해주시겠어요?

@chaeyeon-yang

2023-09-02 06:56 UTC, ShinChanU approved these changes

2023-09-03 10:13 UTC, heehminh requested changes

2023-09-03 10:13 UTC, heehminh commented on src/components/organisms/Header/HeaderContainer.tsx
> +      <HeaderContents isLogin={false} />
isLogin false 일때가 로그인된 상태로 매핑되어있는것 같습니다!

2023-09-03 10:13 UTC, heehminh commented on src/components/pages/rentalOffice/RentalOfficePage.tsx
> +        <LocationClassificationBtn classifications={classificationName} />
제 local에서 봤을 땐 여기서 에러나네요...!
Type '{ name: string; }[]' is not assignable to type 'TClassification[]'.
  Type '{ name: string; }' is missing the following properties from type 'TClassification': id, type, latitude, longitude

2023-09-04 04:05 UTC, chaeyeon-yang commented on src/components/pages/rentalOffice/RentalOfficePage.tsx
> +        <LocationClassificationBtn classifications={classificationName} />
아! 제가 이 부분을 못고쳤네요 다시 고쳐서 커밋했습니다

2023-09-04 07:23 UTC, chaeyeon-yang commented on src/components/organisms/Header/HeaderContainer.tsx
> +      <HeaderContents isLogin={false} />
날카로우시네요 수정하겠습니다

2023-09-04 07:24 UTC, heehminh commented on src/components/molecules/MobileMenu/index.tsx
> +          {isLogin ? (
여기서 isLogin ? A : B 이렇게 작성해주셨는데 A, B 순서를 변경하면 알맞게 동작할 것 같습니다!

2023-09-04 10:05 UTC, chaeyeon-yang commented on src/components/molecules/MobileMenu/index.tsx
> +          {isLogin ? (
감사합니다!!

2023-09-04 10:56 UTC, heehminh approved these changes

2023-09-04 11:09 UTC, chaeyeon-yang commented on src/components/atoms/LocationClassificationBtn/index.tsx
> +  classifications: {
네 수정했습니다!

2023-09-04 11:45 UTC, LeeJSYS approved these changes

2023-09-04 11:48 UTC, merged