Feat, Refactor, Style: PR 관련 피드백 반영, 로그인 기능 구현
Upbrella/Upbrella_front pull request #87
Opened 2023-09-04 04:15 UTC by LeeJSYS

### PR Type

- [ ] 기능 개발 (Feature)
- [ ] 코드 스타일 변경 (Code style update) (formatting, local variables)
- [ ] 화면 작업 (Style, CSS)
- [ ] 리팩토링 (no functional changes, no api changes)
- [ ] 버그수정 (Bugfix)
- [ ] 빌드, 배포 관련 변경 (Build, Deploy)
- [ ] 문서 작업 (Docs)
- [ ] 그 외 (ETC)

## 작업 내용

## Before

## After

## To Reviewers (참고 사항, 첨부 자료 등)
지난 mypage 관련 PR의 style, refactoring 관련 피드백 반영했습니다.
로그인 기능 구현입니다. (아직 상태관리 완성하지 못했습니다.) - 목요일에 기능확인까지 했었습니다.

2023-09-04 11:17 UTC, ShinChanU commented on src/components/pages/Login/LoginRedirectPage/index.tsx
> +    await $axios.get(`/users/oauth/login?code=${code}`, { withCredentials: true });
withCredentials 이 부분은 백엔드 분들이 넣어달라고 하신 부분인가요? 

@LeeJSYS

2023-09-05 02:22 UTC, LeeJSYS commented on src/components/pages/Login/LoginRedirectPage/index.tsx
> +    await $axios.get(`/users/oauth/login?code=${code}`, { withCredentials: true });
이부분은 제가 추가했습니다
withCredentials 추가를 안하면 이후의 `users/login`요청에서 400에러가 발생합니다.
 withCredentials 추가를 안했을때 첫번째 사진과 같이`/users/oauth/login?code=${code}`로 보내는 get 요청의 응답으로 쿠키가 잘 발급되지만 
<img width="1156" alt="image" src="https://github.com/UPbrella/UPbrella_front/assets/120862683/422c2952-fc13-417c-8037-774862428b64">

두번째 `users/login` 로의 get요청에서 request header에 첫 요청에서 발급된 쿠키가 제대로 담기질 않습니다. (두번째 요청에 withCredentials 를 추가했음에도 불구하고)
<img width="1156" alt="image" src="https://github.com/UPbrella/UPbrella_front/assets/120862683/7293ea7e-7119-4dd1-9a2a-07d8668a32f9">
application 탭에서 확인해보니까 이전 요청에서 받은 쿠키가 브라우저에 저장되지 않더라구요

첫번째 요청에withCredentials 를 추가하면 사진과 같이 두번째 요청에서 쿠키가 request header에 잘 담기게 됩니다.
<img width="1160" alt="image" src="https://github.com/UPbrella/UPbrella_front/assets/120862683/da2bd1dd-e029-49ea-b46c-29fcfc25763e">

제 생각에도 첫번째 요청에서는 withCredentials이 없어도 response header에 set-cookie가 들어와도 되어야하는것이 아닌가 생각했는데 찬우님께서 말씀해주셔서 찾아보니
sameSite option과 CORS 설정때문에 withCredentials 설정이 있어야 브라우저에도 쿠키가 제대로 저장된다고 하네요!
감사합니다!

https://gyuturn.tistory.com/74

2023-09-05 08:13 UTC, heehminh approved these changes

2023-09-05 08:13 UTC, heehminh commented on src/components/molecules/Mypage/MypageRentList/index.tsx
> +              <MypageRentSection rentInfo={rent} />
MypageRentSection에서 필요한 props들이 정의가 안된것같습니다!

2023-09-05 08:13 UTC, heehminh commented on src/components/organisms/Mypage/MypageLeftCard/index.tsx
> +import ProfileRent, { TProfileInfo } from "@/components/atoms/Mypage/ProfileRent";
TProfileInfo에서 에러나는데 확인해보니까 ProfileInfoProps로 선언하신 것 같습니다

2023-09-05 08:16 UTC, heehminh requested changes
https://github.com/UPbrella/UPbrella_front/pull/87#discussion_r1315535330

2023-09-05 13:22 UTC, ShinChanU commented on src/components/pages/Login/LoginRedirectPage/index.tsx
> +    await $axios.get(`/users/oauth/login?code=${code}`, { withCredentials: true });
그렇군요 ! 자세한 설명 감사합니다 !
@LeeJSYS

2023-09-05 13:23 UTC, ShinChanU approved these changes

2023-09-06 01:58 UTC, chaeyeon-yang commented on src/components/pages/Login/LoginRedirectPage/index.tsx
> +    await $axios.get(`/users/oauth/login?code=${code}`, { withCredentials: true });
설명 감사합니다!! @LeeJSYS

2023-09-06 02:15 UTC, chaeyeon-yang approved these changes
수고하셨습니다~!!!

2023-09-06 05:16 UTC, heehminh approved these changes

2023-09-06 06:54 UTC, merged