feat: 대분류 태그 별 협업 지점 목록
Upbrella/Upbrella_front pull request #93
Opened 2023-09-08 01:52 UTC by chaeyeon-yang

### PR Type

- [x] 기능 개발 (Feature)
- [ ] 코드 스타일 변경 (Code style update) (formatting, local variables)
- [x] 화면 작업 (Style, CSS)
- [ ] 리팩토링 (no functional changes, no api changes)
- [ ] 버그수정 (Bugfix)
- [ ] 빌드, 배포 관련 변경 (Build, Deploy)
- [ ] 문서 작업 (Docs)
- [ ] 그 외 (ETC)

## 작업 내용
- 대분류 태그 별 협업 지점 목록 api를 받아와 화면에 마커로 띄웠습니다.

## Before

## After

<img width="559" alt="스크린샷 2023-09-08 오전 10 38 50" src="https://github.com/UPbrella/UPbrella_front/assets/69382168/d5ec5593-c065-4956-ac58-a3458b4444eb">

<img width="494" alt="스크린샷 2023-09-08 오전 10 12 55" src="https://github.com/UPbrella/UPbrella_front/assets/69382168/d4f636d0-bb42-4118-bf58-bcaa5a0cec73">

## To Reviewers (참고 사항, 첨부 자료 등)
- 현재 다중 클릭시 모든 마커의 크기 스타일이 변경되고 있으므로 한 번에 하나의 마커만 크기가 커지도록 수정해서 다시 pr 올리겠습니다

2023-09-08 03:17 UTC, heehminh requested changes

2023-09-08 03:17 UTC, heehminh commented on src/components/pages/RentalLocation/RentalLocationPage.tsx
> +import MobileCard from "@/components/molecules/MobileCard";
여기 import 하는 부분에서 에러나서 실행이 안됩니다! 현재 MobileCard가 없는 것 같아요

2023-09-09 04:21 UTC, chaeyeon-yang commented on src/components/pages/RentalLocation/RentalLocationPage.tsx
> +import MobileCard from "@/components/molecules/MobileCard";
아 다음 pr에 올려서 실행에 문제가 있는 것 같네요..! 다음 pr 부터는 신경써서 올리겠습니다!

2023-09-09 07:35 UTC, ShinChanU commented on src/hooks/queries/storeQueries.ts
> +// export const useGetStores = () => {
채연님, 이곳 어드민 협업 관리 페이지에서 사용하는 API 인데, 주석 처리한 이유가 있을까요?! 

@chaeyeon-yang

2023-09-09 08:23 UTC, ShinChanU commented on src/components/pages/RentalLocation/RentalLocationPage.tsx
> +    updateMapMarkers();
이 useEffect 라인에서 무한렌더 나오는 것 같네요 ! 한번 확인해주세요 !

![image](https://github.com/UPbrella/UPbrella_front/assets/76439533/5dd5a6c1-125a-456a-a0bb-23bae121a5e3)

@chaeyeon-yang

2023-09-10 08:45 UTC, chaeyeon-yang commented on src/hooks/queries/storeQueries.ts
> +// export const useGetStores = () => {
아 죄송해요! 제가 쓴 코드인줄 알고 주석처리했습니다! 다시 주석 해제할게요

2023-09-10 12:18 UTC, chaeyeon-yang commented on src/components/pages/RentalLocation/RentalLocationPage.tsx
> +    updateMapMarkers();
아하.. 감사합니다!! 확인할게요

2023-09-11 04:06 UTC, heehminh approved these changes

2023-09-11 12:16 UTC, ShinChanU commented on src/components/pages/RentalLocation/RentalLocationPage.tsx
> +    updateMapMarkers();
수정되면 말씀해주세요 ! 

@chaeyeon-yang

2023-09-13 00:53 UTC, LeeJSYS commented on src/components/pages/RentalLocation/RentalLocationPage.tsx
> +    updateMapMarkers();
@chaeyeon-yang 혹시 수정이 되었나용?

2023-09-13 01:06 UTC, LeeJSYS commented on src/hooks/queries/storeQueries.ts
> +// export const useGetStores = () => {
@ShinChanU 
찬우님 이부분에서 에러떠서 채연님 그다음 PR에서 화면이 안뜨더라구요..!

2023-09-13 01:09 UTC, chaeyeon-yang commented on src/components/pages/RentalLocation/RentalLocationPage.tsx
> +    updateMapMarkers();
@LeeJSYS 네 방금 수정했습니다!

2023-09-13 01:11 UTC, LeeJSYS commented on src/hooks/queries/storeQueries.ts
> +// export const useGetStores = () => {
@ShinChanU 
아닙니다 죄송합니다 제 착각이었습니다..^^

2023-09-13 01:36 UTC, LeeJSYS requested changes

2023-09-13 01:36 UTC, LeeJSYS commented on src/hooks/queries/storeQueries.ts
> +import { getClassifications, getSubClassifications, getClassificationsStore } from "@/api/storeApi";
@chaeyeon-yang 
이부분에서 빠진 getStores를 추가해야할 것 같습니다..!

2023-09-13 01:36 UTC, LeeJSYS commented on src/components/pages/RentalLocation/RentalLocationPage.tsx
> +  const updateMapMarkers = useCallback(() => {
@chaeyeon-yang 
위에서 useCallback이 선언되어있지 않아서 에러뜹니다!c

추가하면 무한렌더링문제도 잘 해결되네요!!

2023-09-13 11:01 UTC, ShinChanU approved these changes

2023-09-13 11:01 UTC, LeeJSYS approved these changes

2023-09-13 11:01 UTC, merged