Style/rental office
Upbrella/Upbrella_front pull request #94
Opened 2023-09-08 02:02 UTC by chaeyeon-yang

### PR Type

- [ ] 기능 개발 (Feature)
- [ ] 코드 스타일 변경 (Code style update) (formatting, local variables)
- [x] 화면 작업 (Style, CSS)
- [ ] 리팩토링 (no functional changes, no api changes)
- [ ] 버그수정 (Bugfix)
- [ ] 빌드, 배포 관련 변경 (Build, Deploy)
- [ ] 문서 작업 (Docs)
- [ ] 그 외 (ETC)

## 작업 내용

- 협업 지점 마커 클릭시 뜨는 바텀시트 화면 작업

## Before

- sm(maxWidth: 360px) 에서의 모바일 헤더 패딩 미적용 문제 

<img width="500" alt="스크린샷 2023-09-08 오전 10 23 49" src="https://github.com/UPbrella/UPbrella_front/assets/69382168/a274e9ba-10b3-4d37-9b94-5f00c27cdfa0">

## After

- sm(maxWidth: 360px) 에서의 모바일 헤더 패딩 적용
<img width="666" alt="스크린샷 2023-09-08 오전 10 26 50" src="https://github.com/UPbrella/UPbrella_front/assets/69382168/758fb32c-9c4f-434e-b5bf-067c6d4c5343">

- 협업 지점 마커 클릭시 나오는 바텀 시트 

<img width="455" alt="스크린샷 2023-09-08 오전 10 27 10" src="https://github.com/UPbrella/UPbrella_front/assets/69382168/20407cda-db33-48e4-8d42-197de4a13e92">

<img width="574" alt="스크린샷 2023-09-08 오전 10 27 30" src="https://github.com/UPbrella/UPbrella_front/assets/69382168/286d643a-987e-4339-a3dc-7d4f98e380b8">

## To Reviewers (참고 사항, 첨부 자료 등)

2023-09-08 03:33 UTC, heehminh requested changes

2023-09-08 03:33 UTC, heehminh commented on src/components/atoms/MobileCardInfo/index.tsx
> +      <div className="mt-18 text-gray-700">
여기 marginTop 없어야 할 것 같습니다!

2023-09-08 03:33 UTC, heehminh approved these changes

2023-09-08 03:34 UTC, heehminh approved these changes

2023-09-09 06:00 UTC, chaeyeon-yang commented on src/components/atoms/MobileCardInfo/index.tsx
> +      <div className="mt-18 text-gray-700">
수정했습니다!

2023-09-10 15:22 UTC, ShinChanU approved these changes

2023-09-13 01:42 UTC, LeeJSYS reviewed
<img width="1248" alt="image" src="https://github.com/UPbrella/UPbrella_front/assets/120862683/cae383ac-75ad-41eb-89af-75c8d418cd63">
제쪽에서 테스트할때는 마커를 눌러도 바텀시트가 안보이네요..!
network 탭에서 보면 메타몽 이미지 들어오는 것 보면 데이터자체는 넘어오는데 보이지만 않는것같습니다

2023-09-13 01:42 UTC, LeeJSYS commented on src/App.tsx
> +        <div className="max-w-[1440px] min-h-[100vh] px-40 mx-auto flex flex-col sm:px-0">
@chaeyeon-yang 
제쪽에서 테스트해보면 사진처럼 360일때까지는 padding이 없다가
<img width="496" alt="image" src="https://github.com/UPbrella/UPbrella_front/assets/120862683/1732a1d8-13fc-4df8-a6ba-07a3664a5afb">
361이 되면서부터 padding이 생기는데 
<img width="490" alt="image" src="https://github.com/UPbrella/UPbrella_front/assets/120862683/b5c6ebbf-4972-44d6-8ab9-2d492b5c63ff">
의도된대로 동작하는게 맞나용?

2023-09-13 11:10 UTC, LeeJSYS approved these changes

2023-09-13 11:10 UTC, merged